import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import HomeSlider from '../component/ui/home/homeSlider'
import Nxtt from '../component/ui/home/nxtt'
import Footer from '../component/ui/home/footer'

export default function Home() {
  return (
    <div className="bg-[#050011]">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="text-gray-200  w-full flex  bg-[url('/backgrounds/page-cover.png')] \
      h-[4444px] bg-contain bg-no-repeat flex-col items-center ">
        <nav className='max-w-7xl w-full flex max-h-14 items-center justify-between my-3 sticky top-0 lg:px-10
         '>
          <div className='flex m-3 flex-none items-center '>
            <img src="/next_earth.svg" alt="" className='w-8 h-8 mt-1 mr-1 ' />
            <div className='flex-col flex w-28 text-xs font-bold mt-1 '>
              META X LAND
            </div>
          </div>
          <div className='lg:flex hidden  w-full text-xs font-bold h-10 items-center flex-2 lg:ml-10'>
            <button className='mx-2'>
              MAP
            </button>
            <button className='mx-2'>
              LAUNCHPAD
            </button>
            <button className='mx-4'>
              NXTT
            </button>
            <button className='mx-2'>
              CONTACT US
            </button>
            <button className='mx-2'>
              WE'RE HIRING!
            </button>
          </div>
          <div className='flex text-xs font-bold h-10 flex-1 justify-end'>
            <button type="login" className='mx-2 my-1 border border-white rounded-full px-4  '>LOGIN</button>
            <button type="login" className='lg:block hidden my-1 whitespace-nowrap mx-2 rounded-full px-4 bg-gradient-to-r via-purple-700 to-purple-600 from-pink-600'>CONNECT WALLET </button>
          </div>
        </nav>

        <div className='w-full flex justify-start mt-36'>
          <div className='lg:w-1/2  max-w-md lg:ml-16 px-6'>

            <div className='text-4xl font-bold  '>
              The First True Land Ownership Platform in the Metaverse
            </div>
            <div className='font-semibold text-sm mt-10'>
              With the Power of NFT's, we are building a platform for users to purchase, develop, and sell virtual land mapped onto the Earth. By combining your entrepreneurial spirit with our infrastructure, our Next Earth will create true equality at every level.
            </div>
          </div>
        </div>
        <div className=' mt-14 flex justify-start w-full'>
          <div className='flex justify-start w-full lg:ml-24 md:flex-row flex-col mx-6'>
            <button type="link" className='rounded-full px-6 text-xs font-bold lg:mx-0 mx-6 text-center py-3 flex items-center bg-gradient-to-r via-purple-700 to-purple-600 from-pink-600 justify-center'>
              <img src="/svg/shopping_cart.svg" alt="" className='invert w-5 mr-1' />
              BUY LAND
            </button>
            <button type="link" className='rounded-full border border-white px-6 text-xs font-bold py-3 mx-6 mt-3 md:mt-0'>HOW TO BUY LAND</button>
          </div>
        </div>


        {/* <HomeSlider />

        <Nxtt /> */}
        <div className='w-full'>
          
        <Footer />
        </div>




      </main>
      <div className='bg-white'>
        <footer className={styles.footer} >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </footer>
      </div>
    </div>
  )
}
